#!/usr/bin/env bash
# Generate the full grid of GAP traces: 6 kernels × 4 inputs = 24 traces.
#
# Usage: scripts/gen_all_gap_traces.sh [cap_M] [parallelism] [inputs_csv] [kernels_csv]
#   cap_M:        instruction trace cap in millions, default 50
#   parallelism:  number of concurrent Pin processes, default 4
#   inputs_csv:   comma-separated input names, default kron18,kron20,urand18,urand20
#   kernels_csv:  comma-separated kernels, default bfs,pr,sssp,bc,cc,tc
#
# Each trace is generated by scripts/gen_gap_trace.sh (which handles ASLR
# disable, Pin invocation, and xz compression). Already-present traces are
# skipped, so the script is safely re-runnable.
#
# Wall-clock estimate at default cap=50M on the 22-core host:
#   Pin per trace ~ 55 s; xz per trace ~ 5-8 min single-thread.
#   With parallelism=4, full grid ~ 60-90 min.
#
# Disk peak: parallelism × 3 GB raw temp files = ~12 GB at parallelism=4.
# All raw files are removed by gen_gap_trace.sh after xz.

set -euo pipefail

CAP_M="${1:-50}"
PAR="${2:-4}"
INPUTS_CSV="${3:-kron18,kron20,urand18,urand20}"
KERNELS_CSV="${4:-bfs,pr,sssp,bc,cc,tc}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

IFS=',' read -r -a KERNELS <<< "$KERNELS_CSV"
IFS=',' read -r -a INPUTS <<< "$INPUTS_CSV"
LOG_DIR="${REPO_ROOT}/traces/gap/logs"
mkdir -p "$LOG_DIR"

# Build the worklist as (kernel, input) pairs, skipping existing outputs.
declare -a TODO=()
for k in "${KERNELS[@]}"; do
  for i in "${INPUTS[@]}"; do
    if [[ -f "${REPO_ROOT}/traces/gap/${k}_${i}.trace.xz" ]]; then
      echo "[skip] ${k}_${i} already done"
      continue
    fi
    TODO+=("${k}|${i}")
  done
done

if [[ ${#TODO[@]} -eq 0 ]]; then
  echo "All requested traces already present — nothing to do."
  exit 0
fi

echo "=== Generating ${#TODO[@]} GAP traces, cap=${CAP_M}M, par=${PAR} ==="
echo "kernels: ${KERNELS[*]}"
echo "inputs:  ${INPUTS[*]}"

# Use xargs -P for parallel scheduling.
START=$(date +%s)
printf '%s\n' "${TODO[@]}" | xargs -I{} -P "$PAR" bash -c '
  pair="$1"
  kernel="${pair%%|*}"
  input="${pair##*|}"
  log="'"$LOG_DIR"'/${kernel}_${input}.log"
  if "'"$SCRIPT_DIR"'/gen_gap_trace.sh" "$kernel" "$input" "'"$CAP_M"'" >> "$log" 2>&1; then
    echo "[done] ${kernel}_${input}"
  else
    echo "[FAIL] ${kernel}_${input} (see $log)" >&2
    exit 1
  fi
' _ {}

END=$(date +%s)
echo
echo "=== Grid done in $((END-START))s ==="

# Inventory.
echo
echo "=== Trace inventory ==="
ls -lh "${REPO_ROOT}/traces/gap/"*.trace.xz 2>/dev/null | awk '{print $5, $9}'
